### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by KeyWaveTree** [alexfirst09/HUFS-open-sw_test#5]
수정한 코드 확인 부탁 드려요.

**Comment by KeyWaveTree** [comment]
d58ef034a7129c9d0fa9e519170a024fc420ef72

**Comment by alexfirst09** [comment]
확인했습니다
코멘트 남겼으니 확인 부탁드립니다

d58ef034a7129c9d0fa9e519170a024fc420ef72
